apiVersion: v1
kind: Service
metadata:
  name: copilot-api
  namespace: default
spec:
  type: NodePort
  selector:
    app: copilot-api
  ports:
    - port: 4141
      targetPort: 4141
      nodePort: 30141
